version: "2.1"
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - {{ config }}:/config
      - {{ movies }}:/movies #optional
      - {{ downloads }}:/downloads #optional
    network_mode: container:gluetun
    restart: always