name: Build and Upload to PyPI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build and Upload to PyPI
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
          TWINE_REPOSITORY: https://test.pypi.org/legacy/
